### ISSUE TITLE
1122 TODO

### ISSUE THREAD

**Issue by jjimini98** [jjimini98/graduation#11]
### 1122 TODO

- [x] ubuntu 서버로 이동 (vscode remote ssh) 
- [x] gpt 모델 filezilla로 이동 
- [x] django 서버 띄우고 윈도우에서 접속 되는지 확인
- [x] django 코드 수정 (브랜치 따서) 
- [x] sentence similarity 코드 수정
