### ISSUE TITLE
1119 TODO

### ISSUE THREAD

**Issue by jjimini98** [jjimini98/graduation#8]
**1119 TODO**

- [x] gpt_model.py 코드 수정 
- [x] gpt_dialog.py 코드 수정 -> 내 컴퓨터에서 돌려도 돌아가게끔..
- [x] gpt_test.ipynb 필요한가..? 필요하면 정리필요
- [x] gpt_test.py 코드 수정
- [x] TextDataSet.py 코드 수정하고 업로드 
- [x] Django 부분 확인해야함
